export const FIAT_CURRENCIES = [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", flag: "🇧🇦" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", flag: "🇧🇧" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭" },
  { code: "BIF", name: "Burundian Franc", symbol: "Fr", flag: "🇧🇮" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", flag: "🇧🇳" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", flag: "🇧🇼" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  { code: "CDF", name: "Congolese Franc", symbol: "Fr", flag: "🇨🇩" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", flag: "🇨🇭" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fr", flag: "🇩🇯" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯" },
  { code: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean Franc", symbol: "Fr", flag: "🇬🇳" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgystani Som", symbol: "с", flag: "🇰🇬" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  { code: "KMF", name: "Comorian Franc", symbol: "Fr", flag: "🇰🇲" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flag: "🇱🇧" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", flag: "🇱🇰" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", flag: "🇱🇾" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese Pataca", symbol: "P", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", flag: "🇴🇲" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", flag: "🇵🇪" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs", flag: "🇵🇰" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", flag: "🇵🇾" },
  { code: "QAR", name: "Qatari Rial", symbol: "ر.ق", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", flag: "🇷🇸" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", flag: "🇸🇦" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", flag: "🇸🇩" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", flag: "🇸🇸" },
  { code: "SYP", name: "Syrian Pound", symbol: "£S", flag: "🇸🇾" },
  { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", flag: "🇺🇿" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.S", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "Fr", flag: "🌍" },
  { code: "XOF", name: "West African CFA Franc", symbol: "Fr", flag: "🌍" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
] as const;

export type FiatCurrencyCode = typeof FIAT_CURRENCIES[number]["code"];

export function getFiatCurrency(code: string) {
  return FIAT_CURRENCIES.find(c => c.code === code) ?? { code, name: code, symbol: code, flag: "🌐" };
}

export function getFlagUrl(flag: string, size: "sm" | "md" = "md"): string {
  try {
    const points = [...flag].map(c => c.codePointAt(0)!);
    if (points.length === 2 && points[0] >= 0x1F1E6 && points[0] <= 0x1F1FF) {
      const cc = points.map(p => String.fromCharCode(p - 0x1F1E6 + 65)).join("").toLowerCase();
      return size === "sm"
        ? `https://flagcdn.com/24x18/${cc}.png`
        : `https://flagcdn.com/w40/${cc}.png`;
    }
  } catch {}
  return "";
}

export const NATIONALITY_TO_CURRENCY: Record<string, string> = {
  AE: "AED", AF: "AFN", AL: "ALL", AM: "AMD", AO: "AOA",
  AR: "ARS", AU: "AUD", AW: "AWG", AZ: "AZN",
  BA: "BAM", BB: "BBD", BD: "BDT", BG: "BGN", BH: "BHD",
  BI: "BIF", BN: "BND", BO: "BOB", BR: "BRL", BW: "BWP",
  BY: "BYN", BZ: "BZD",
  CA: "CAD", CD: "CDF", CH: "CHF", CL: "CLP", CN: "CNY",
  CO: "COP", CR: "CRC", CV: "CVE", CZ: "CZK",
  DE: "EUR", DJ: "DJF", DK: "DKK", DO: "DOP", DZ: "DZD",
  EG: "EGP", ER: "ERN", ES: "EUR", ET: "ETB",
  FJ: "FJD", FR: "EUR",
  GB: "GBP", GE: "GEL", GH: "GHS", GM: "GMD", GN: "GNF", GT: "GTQ",
  HK: "HKD", HN: "HNL", HR: "EUR", HT: "HTG", HU: "HUF",
  ID: "IDR", IE: "EUR", IN: "INR", IQ: "IQD", IS: "ISK", IT: "EUR",
  JO: "JOD", JP: "JPY",
  KE: "KES", KG: "KGS", KH: "KHR", KM: "KMF", KR: "KRW",
  KW: "KWD", KZ: "KZT",
  LA: "LAK", LB: "LBP", LK: "LKR", LS: "LSL", LY: "LYD",
  MA: "MAD", MD: "MDL", MG: "MGA", MK: "MKD", MM: "MMK",
  MN: "MNT", MO: "MOP", MR: "MRU", MW: "MWK", MX: "MXN", MY: "MYR",
  NG: "NGN", NO: "NOK", NP: "NPR", NZ: "NZD",
  OM: "OMR",
  PE: "PEN", PH: "PHP", PK: "PKR", PL: "PLN", PY: "PYG",
  QA: "QAR",
  RO: "RON", RS: "RSD", RU: "RUB",
  SA: "SAR", SD: "SDG", SE: "SEK", SG: "SGD", SS: "SSP", SY: "SYP",
  TH: "THB", TJ: "TJS", TM: "TMT", TN: "TND", TR: "TRY",
  TW: "TWD", TZ: "TZS",
  UA: "UAH", UG: "UGX", US: "USD", UY: "UYU", UZ: "UZS",
  VE: "VES", VN: "VND",
  YE: "YER",
  ZA: "ZAR", ZM: "ZMW",
};
