uploads = []
generated = []

[[outputs]]
id = "fstNBmE_7d3QqXFzDqtiq"
uri = "file://xendrx-deploy.zip"
type = "unspecified"
title = "xendrx-deploy.zip"

[[outputs]]
id = "HIi-DP2vtTRK-biqgIPkO"
uri = "file://xendrx-deploy.tar.gz"
type = "unspecified"
title = "xendrx-deploy.tar.gz — email send fixed"
